/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Nat8;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeviceId = IDL.Nat8;
export const LightDevice = IDL.Record({
  'isOn' : IDL.Bool,
  'name' : IDL.Text,
  'brightness' : IDL.Nat8,
  'roomId' : RoomId,
});
export const RoomInfo = IDL.Record({
  'id' : RoomId,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'isHidden' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SensorStats = IDL.Record({
  'temperature' : IDL.Float64,
  'humidity' : IDL.Float64,
});
export const RoomSwitchInfo = IDL.Record({
  'totalDevices' : IDL.Nat,
  'activeDevices' : IDL.Nat,
});
export const SupportTicket = IDL.Record({
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateSensors' : IDL.Func([RoomId, IDL.Float64, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDevice' : IDL.Func(
      [DeviceId, IDL.Text, RoomId, IDL.Bool, IDL.Nat8],
      [],
      [],
    ),
  'createRoom' : IDL.Func([RoomId, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'getAllDevices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DeviceId, LightDevice))],
      ['query'],
    ),
  'getAllRooms' : IDL.Func([], [IDL.Vec(RoomInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevices' : IDL.Func(
      [RoomId],
      [IDL.Vec(IDL.Tuple(DeviceId, LightDevice))],
      ['query'],
    ),
  'getRoomInfo' : IDL.Func([RoomId], [IDL.Opt(RoomInfo)], ['query']),
  'getRoomSensorStats' : IDL.Func([RoomId], [IDL.Opt(SensorStats)], ['query']),
  'getRoomSwitchInfo' : IDL.Func(
      [RoomId],
      [IDL.Opt(RoomSwitchInfo)],
      ['query'],
    ),
  'getSupportTicket' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SupportTicket)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBrightness' : IDL.Func([DeviceId, IDL.Nat8], [IDL.Bool], []),
  'setRoomHidden' : IDL.Func([RoomId, IDL.Bool], [], []),
  'submitSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleAllDevicesInRoom' : IDL.Func([RoomId, IDL.Bool], [IDL.Bool], []),
  'toggleDevice' : IDL.Func([DeviceId], [IDL.Bool], []),
  'updateRoomSettings' : IDL.Func([RoomId, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Nat8;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeviceId = IDL.Nat8;
  const LightDevice = IDL.Record({
    'isOn' : IDL.Bool,
    'name' : IDL.Text,
    'brightness' : IDL.Nat8,
    'roomId' : RoomId,
  });
  const RoomInfo = IDL.Record({
    'id' : RoomId,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'isHidden' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SensorStats = IDL.Record({
    'temperature' : IDL.Float64,
    'humidity' : IDL.Float64,
  });
  const RoomSwitchInfo = IDL.Record({
    'totalDevices' : IDL.Nat,
    'activeDevices' : IDL.Nat,
  });
  const SupportTicket = IDL.Record({
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateSensors' : IDL.Func([RoomId, IDL.Float64, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDevice' : IDL.Func(
        [DeviceId, IDL.Text, RoomId, IDL.Bool, IDL.Nat8],
        [],
        [],
      ),
    'createRoom' : IDL.Func([RoomId, IDL.Text, IDL.Text, IDL.Bool], [], []),
    'getAllDevices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DeviceId, LightDevice))],
        ['query'],
      ),
    'getAllRooms' : IDL.Func([], [IDL.Vec(RoomInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevices' : IDL.Func(
        [RoomId],
        [IDL.Vec(IDL.Tuple(DeviceId, LightDevice))],
        ['query'],
      ),
    'getRoomInfo' : IDL.Func([RoomId], [IDL.Opt(RoomInfo)], ['query']),
    'getRoomSensorStats' : IDL.Func(
        [RoomId],
        [IDL.Opt(SensorStats)],
        ['query'],
      ),
    'getRoomSwitchInfo' : IDL.Func(
        [RoomId],
        [IDL.Opt(RoomSwitchInfo)],
        ['query'],
      ),
    'getSupportTicket' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SupportTicket)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBrightness' : IDL.Func([DeviceId, IDL.Nat8], [IDL.Bool], []),
    'setRoomHidden' : IDL.Func([RoomId, IDL.Bool], [], []),
    'submitSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleAllDevicesInRoom' : IDL.Func([RoomId, IDL.Bool], [IDL.Bool], []),
    'toggleDevice' : IDL.Func([DeviceId], [IDL.Bool], []),
    'updateRoomSettings' : IDL.Func([RoomId, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };