/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeviceId = number;
export interface LightDevice {
  'isOn' : boolean,
  'name' : string,
  'brightness' : number,
  'roomId' : RoomId,
}
export type RoomId = number;
export interface RoomInfo {
  'id' : RoomId,
  'name' : string,
  'color' : string,
  'isHidden' : boolean,
  'isRunning' : boolean,
}
export interface RoomSwitchInfo {
  'totalDevices' : bigint,
  'activeDevices' : bigint,
}
export interface SensorStats { 'temperature' : number, 'humidity' : number }
export interface SupportTicket {
  'subject' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateSensors' : ActorMethod<[RoomId, number, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDevice' : ActorMethod<
    [DeviceId, string, RoomId, boolean, number],
    undefined
  >,
  'createRoom' : ActorMethod<[RoomId, string, string, boolean], undefined>,
  'generateNextDeviceId' : ActorMethod<[], number>,
  'getAllDevices' : ActorMethod<[], Array<[DeviceId, LightDevice]>>,
  'getAllRoomSummaries' : ActorMethod<[], Array<RoomInfo>>,
  'getAllRooms' : ActorMethod<[], Array<RoomInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDevices' : ActorMethod<[RoomId], Array<[DeviceId, LightDevice]>>,
  'getRoomCount' : ActorMethod<[], bigint>,
  'getRoomInfo' : ActorMethod<[RoomId], [] | [RoomInfo]>,
  'getRoomSensorStats' : ActorMethod<[RoomId], [] | [SensorStats]>,
  'getRoomSummariesRange' : ActorMethod<[bigint, bigint], Array<RoomInfo>>,
  'getRoomSwitchInfo' : ActorMethod<[RoomId], [] | [RoomSwitchInfo]>,
  'getRoomsForCount' : ActorMethod<[bigint], Array<RoomInfo>>,
  'getSupportTicket' : ActorMethod<[Principal], [] | [SupportTicket]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccess' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBrightness' : ActorMethod<[DeviceId, number], boolean>,
  'setRoomCount' : ActorMethod<[bigint], undefined>,
  'setRoomHidden' : ActorMethod<[RoomId, boolean], undefined>,
  'setRoomRunning' : ActorMethod<[RoomId, boolean], undefined>,
  'submitSupportTicket' : ActorMethod<[string, string], undefined>,
  'toggleAllDevicesInRoom' : ActorMethod<[RoomId, boolean], boolean>,
  'toggleDevice' : ActorMethod<[DeviceId], boolean>,
  'toggleRoomRunningState' : ActorMethod<[RoomId], boolean>,
  'updateRoomSettings' : ActorMethod<[RoomId, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];