/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SupportTicket {
    subject: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
}
export interface SensorStats {
    temperature: number;
    humidity: number;
}
export type DeviceId = number;
export interface LightDevice {
    isOn: boolean;
    name: string;
    brightness: number;
    roomId: RoomId;
}
export interface RoomSwitchInfo {
    totalDevices: bigint;
    activeDevices: bigint;
}
export type RoomId = number;
export interface RoomInfo {
    id: RoomId;
    name: string;
    color: string;
    isHidden: boolean;
    isRunning: boolean;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateSensors(roomId: RoomId, temperature: number, humidity: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDevice(deviceId: DeviceId, name: string, roomId: RoomId, isOn: boolean, brightness: number): Promise<void>;
    createRoom(roomId: RoomId, name: string, color: string, isHidden: boolean): Promise<void>;
    generateNextDeviceId(): Promise<number>;
    getAllDevices(): Promise<Array<[DeviceId, LightDevice]>>;
    getAllRoomSummaries(): Promise<Array<RoomInfo>>;
    getAllRooms(): Promise<Array<RoomInfo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDevices(roomId: RoomId): Promise<Array<[DeviceId, LightDevice]>>;
    getRoomCount(): Promise<bigint>;
    getRoomInfo(roomId: RoomId): Promise<RoomInfo | null>;
    getRoomSensorStats(roomId: RoomId): Promise<SensorStats | null>;
    getRoomSummariesRange(fromIndex: bigint, toIndex: bigint): Promise<Array<RoomInfo>>;
    getRoomSwitchInfo(roomId: RoomId): Promise<RoomSwitchInfo | null>;
    getRoomsForCount(count: bigint): Promise<Array<RoomInfo>>;
    getSupportTicket(user: Principal): Promise<SupportTicket | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccess(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setBrightness(deviceId: DeviceId, brightness: number): Promise<boolean>;
    setRoomCount(count: bigint): Promise<void>;
    setRoomHidden(roomId: RoomId, isHidden: boolean): Promise<void>;
    setRoomRunning(roomId: RoomId, isRunning: boolean): Promise<void>;
    submitSupportTicket(subject: string, description: string): Promise<void>;
    toggleAllDevicesInRoom(roomId: RoomId, turnOn: boolean): Promise<boolean>;
    toggleDevice(deviceId: DeviceId): Promise<boolean>;
    toggleRoomRunningState(roomId: RoomId): Promise<boolean>;
    updateRoomSettings(roomId: RoomId, name: string, color: string): Promise<void>;
}
import type { RoomInfo as _RoomInfo, RoomSwitchInfo as _RoomSwitchInfo, SensorStats as _SensorStats, SupportTicket as _SupportTicket, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateSensors(arg0: RoomId, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateSensors(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateSensors(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDevice(arg0: DeviceId, arg1: string, arg2: RoomId, arg3: boolean, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDevice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDevice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createRoom(arg0: RoomId, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async generateNextDeviceId(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.generateNextDeviceId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateNextDeviceId();
            return result;
        }
    }
    async getAllDevices(): Promise<Array<[DeviceId, LightDevice]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices();
            return result;
        }
    }
    async getAllRoomSummaries(): Promise<Array<RoomInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoomSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoomSummaries();
            return result;
        }
    }
    async getAllRooms(): Promise<Array<RoomInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevices(arg0: RoomId): Promise<Array<[DeviceId, LightDevice]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevices(arg0);
            return result;
        }
    }
    async getRoomCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomCount();
            return result;
        }
    }
    async getRoomInfo(arg0: RoomId): Promise<RoomInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomInfo(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomInfo(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomSensorStats(arg0: RoomId): Promise<SensorStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomSensorStats(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomSensorStats(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomSummariesRange(arg0: bigint, arg1: bigint): Promise<Array<RoomInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomSummariesRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomSummariesRange(arg0, arg1);
            return result;
        }
    }
    async getRoomSwitchInfo(arg0: RoomId): Promise<RoomSwitchInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomSwitchInfo(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomSwitchInfo(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomsForCount(arg0: bigint): Promise<Array<RoomInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomsForCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomsForCount(arg0);
            return result;
        }
    }
    async getSupportTicket(arg0: Principal): Promise<SupportTicket | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportTicket(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportTicket(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccess(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccess();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setBrightness(arg0: DeviceId, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setBrightness(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBrightness(arg0, arg1);
            return result;
        }
    }
    async setRoomCount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRoomCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRoomCount(arg0);
            return result;
        }
    }
    async setRoomHidden(arg0: RoomId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRoomHidden(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRoomHidden(arg0, arg1);
            return result;
        }
    }
    async setRoomRunning(arg0: RoomId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRoomRunning(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRoomRunning(arg0, arg1);
            return result;
        }
    }
    async submitSupportTicket(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportTicket(arg0, arg1);
            return result;
        }
    }
    async toggleAllDevicesInRoom(arg0: RoomId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAllDevicesInRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAllDevicesInRoom(arg0, arg1);
            return result;
        }
    }
    async toggleDevice(arg0: DeviceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDevice(arg0);
            return result;
        }
    }
    async toggleRoomRunningState(arg0: RoomId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleRoomRunningState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleRoomRunningState(arg0);
            return result;
        }
    }
    async updateRoomSettings(arg0: RoomId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoomSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoomSettings(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomInfo]): RoomInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SensorStats]): SensorStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomSwitchInfo]): RoomSwitchInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupportTicket]): SupportTicket | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
